# Generated by Django 2.2.1 on 2019-06-26 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('username', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserDockerCred',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('docker_registry', models.CharField(max_length=100)),
                ('docker_registry_username', models.CharField(max_length=100)),
                ('docker_registry_password', models.CharField(max_length=100)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.UserModel')),
            ],
        ),
        migrations.CreateModel(
            name='KubernetesConfigModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kube_conf_file', models.TextField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.UserModel')),
            ],
        ),
    ]
